# 创建数组、矩阵

In [8]:
import numpy as np
a=np.array([1,2,3])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
b[1,1]=10
print (a.shape) #数组大小
print (b.shape)
print (a.dtype)#数组类型
print (b)#输出数组


(3,)
(3, 3)
int32
[[ 1  2  3]
 [ 4 10  6]
 [ 7  8  9]]


## 创建结构数组

In [11]:
# encoding:utf-8
import numpy as np

persontype = np.dtype({
  'names': ['name', 'age', 'chinese', 'math', 'english'],
  'formats': ['S32', 'i', 'i', 'i', 'f']
})

peoples = np.array(
  [
    ('zhangfei', 32, 75, 100, 90),
    ('guanyu', 24, 85, 96, 88.5),
    ('zhaoyun', 28, 85, 92, 96.5),
    ('huangzhong', 29, 65, 85, 100)
  ],
  dtype=persontype
)

ages = peoples[:]['age']
chineses = peoples[:]['chinese']
math = peoples[:]['math']
english = peoples[:]['english']

print (np.mean(ages))
print (np.mean(chineses))
print (np.mean(math))
print (np.mean(english))

28.25
77.5
93.25
93.75


# 连续数组创建

In [21]:
x1=np.arange(1,10,2)#分别对应初始值、终值、步长
x2=np.linspace(1,9,5)#分别对应初始值、终值、元素个数
print (x1)
print (x2)
print (x1.shape)
print (x2.shape)
print (x1.dtype)#数组类型
print (x2.dtype)#数组类型

[1 3 5 7 9]
[1. 3. 5. 7. 9.]
(5,)
(5,)
int32
float64


# 算数运算（加减乘除n次方取余）

In [12]:
# encoding:utf-8

import numpy as np

x1 = np.arange(1, 11, 2)  # 默认不包含最终值
x2 = np.linspace(1, 9, 5)  # 默认包含最终值

print (np.add(x1, x2))  # 加法
print (np.subtract(x1, x2))  # 减法
print (np.multiply(x1, x2))  # 乘法
print (np.divide(x1, x2))  # 除法
print (np.power(x1, x2))  # 求N次方x1对应处的x2次方
print (np.remainder(x1, x2))  # 取余

[ 2.  6. 10. 14. 18.]
[0. 0. 0. 0. 0.]
[ 1.  9. 25. 49. 81.]
[1. 1. 1. 1. 1.]
[1.00000000e+00 2.70000000e+01 3.12500000e+03 8.23543000e+05
 3.87420489e+08]
[0. 0. 0. 0. 0.]


# 统计函数

## 计算数组和矩阵的最大值最小值

In [22]:
# encoding:utf-8

import numpy as np

a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

print (np.amin(a))
print (np.amin(a, 0))
print (np.amin(a, 1))

print (np.amax(a))
print (np.amax(a, 0))
print (np.amax(a, 1))

1
[1 2 3]
[1 4 7]
9
[7 8 9]
[3 6 9]
